--Create table stg.Sales
CREATE TABLE stg.Sales (
    Order_Number INT,
    Quantity_Ordered INT,
    Price DECIMAL(10,2),
    OrderLineNumber INT,
    Sales DECIMAL(10,2),
    OrderDate DATE,
    Status NVARCHAR(20),
    Quarter TINYINT,
    Month TINYINT,
    Year INT,
    ProductLine NVARCHAR(50),
    MSRP INT,
    ProductCode NVARCHAR(20),
    CustomerName NVARCHAR(100),
    Phone NVARCHAR(20),
    AddressLine1 NVARCHAR(100),
    AddressLine2 NVARCHAR(100),
    City NVARCHAR(50),
    State NVARCHAR(50),
    PostalCode NVARCHAR(20),
    Country NVARCHAR(50),
    Territory NVARCHAR(10),
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    DealSize NVARCHAR(10)
)
